### ISSUE TITLE
Minty "cannot find module fs/promises"

### ISSUE THREAD

**Issue by bumbleio** [yusefnapora/minty#14]
Really enhoed your NFT hack presentation but 

Followed readme - please advise

test@ubuntu:~/code/ethereum/ARG$ node --version
v12.21.0
test@ubuntu:~/code/ethereum/ARG$ npm --version
6.14.11
test@ubuntu:~/code/ethereum/ARG$ minty
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /home/test/code/ethereum/ARG/minty/minty/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/test/code/ethereum/ARG/minty/minty/src/index.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/test/code/ethereum/ARG/minty/minty/src/index.js' ]
}

**Comment by bumbleio** [comment]
Upgrade node to latest version - fixed issue

**Comment by bumbleio** [comment]
Updated node to latest version
