### ISSUE TITLE
Pinning Issues

### ISSUE THREAD

**Issue by rykci** [yusefnapora/minty#34]
When I try to pin with pinata config I get error:

```
Pinning asset data (ipfs://<MYCID>/mynft.jpeg) for token id 2....
HTTPError: reason: "API_KEY_REVOKED", details: "This API Key has been revoked": 403 Forbidden
    at Object.errorHandler [as handleError] (Desktop/Code/minty/minty/node_modules/ipfs-http-client/src/lib/core.js:91:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client.fetch (/Desktop/Code/minty/minty/node_modules/ipfs-utils/src/http.js:147:9)
    at async Function.ls (Desktop/Code/minty/minty/node_modules/ipfs-http-client/src/pin/remote/index.js:89:22)
    at async Minty.isPinned (Desktop/Code/minty/minty/src/minty.js:458:22)
    at async Minty.pin (/Desktop/Code/minty/minty/src/minty.js:430:20)
    at async Minty.pinTokenData (Desktop/Code/minty/minty/src/minty.js:409:5)
    at async Command.pinNFTData (Desktop/Code/minty/minty/src/index.js:151:37)
    at async Promise.all (index 0)
    at async main (/Desktop/Code/minty/minty/src/index.js:81:3) {
  response: Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: { body: [PassThrough], disturbed: true, error: null },
    [Symbol(Response internals)]: {
      url: 'http://localhost:5001/api/v0/pin/remote/ls?service=pinata&cid=bafybeih5upw7duqwg4s24zbwqkgatwawqr4ayeaspdg5miqxp3t25q2x3e',
      status: 500,
      statusText: 'Internal Server Error',
      headers: [Headers],
      counter: 0
    }
  }
}
```

I see it says API_KEY_REVOKED, but it happens even if I make a new API key.. I get a similar issue as well when I try to switch to nft.storage. 
Also, I see the contract mints Julep Tokens, where does it specify that in the contract? I cannot seem to find it

**Comment by rykci** [comment]
It seems I needed to remove the service from my IPFS service list when I generate a new key.
